### PR TITLE
Add print functionality for browser client

### PR DESCRIPTION
**Pull request by Manish3323**
This PR adds the functionality for printing the generated pdf. [Browser only]

Updated readme too.

### CODE REVIEW

**Comment by Manish3323** [comment]
@dveldhoen i thought print function should reside in this library instead of application code.
Let me know your thoughts as well.

**Comment by Manish3323** [comment]
Also i am not sure, whether browser client typescript type's go in src/lib/easyinvoice.d.ts file or not.  
if yes will update that too.

**Comment by dveldhoen** [comment]
Thanks, we appreciate the contribution. Will have a look as soon as possible. I know the code is a bit mixed up, this was because we were in a hurry to fix a security vulnerability. The next version will contain cleaner code.

**Comment by dveldhoen** [comment]
I made a small change and went with print-js. The code looks cleaner that way.

**Comment by Manish3323** [comment]
I tried it. the print function doesn't exists.

i think it's because .. 
in package json 
`
module: index-module.ts
`
& index-module.ts is pointing to 'src/lib/easyinvoice' instead of `src/browser/browser`..

**Comment by Manish3323** [comment]
do have a look at this.. 
https://github.com/dveldhoen/easyinvoice/pull/97

**Pull request merged**
